AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-sam-typescript-library

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Environment:
      Variables:
        SAMPLE_TABLE: !Ref BooksTable
        ITEM_QUEUE: !Ref WriteQueue
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  getBooksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/GetBooksHandler.getBooksHandler
      Description: A simple example includes a HTTP get method to get all books from a DynamoDB table.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  
  getBookByIdFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/GetBookByIdHandler.getBookByIdHandler
      Description: A simple example includes a HTTP get method to get one book by id from a DynamoDB table.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
  
  putBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/PutBookHandler.putBookHandler
      Description: A simple example includes a HTTP post method to add one book to an SQS queue (to be written to a DynamoDB table later).
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt WriteQueue.QueueName
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  writeBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/WriteBookHandler.writeBookHandler
      Description: A simple example includes an SQS subscription to write queued object to DynamoDB
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      Policies:
        # Give Create/Read/Update/Delete Permissions to the BooksTable, see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#dynamo-db-crud-policy
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      Events:
        # Subscription to primary SQS queue
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WriteQueue.Arn
            BatchSize: 1

  BooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  WriteQueue:
    Type: AWS::SQS::Queue

  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
